Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	# Sincronizar o diretório local com a máquina virtual
	config.vm.synced_folder ".", "/vagrant_data"

	# Definir a máquina K3s Server
	config.vm.define "caalbertS" do |control|
	  control.vm.hostname = "caalbertS"
	  control.vm.network "private_network", ip: "192.168.56.110"
	  control.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	  end

	  # Provisionar a máquina para instalar K3s e as aplicações
	  control.vm.provision "shell", path: "scripts/server/entrypoint.sh"
	end
  end

	# Máquina Worker caalbertSW
# 	config.vm.define "caalbertSW" do |control|
# 	control.vm.hostname = "caalbertSW"
# 	control.vm.network "private_network", ip: "192.168.56.111"
# 	control.vm.provider "virtualbox" do |v|
# 		v.memory = 1024
# 		v.cpus = 2
# 	end
# 	control.vm.provision "shell", path: "scripts/worker/entrypoint.sh"
# 	end
# end