Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	config.vm.synced_folder ".", "/vagrant_data"

	config.vm.define "caalbertS" do |control|
	  control.vm.hostname = "caalbertS"
	  control.vm.network "private_network", ip: "192.168.56.110"
	  control.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	  end

	  # K3s e as apps
	  control.vm.provision "shell", path: "scripts/server/entrypoint.sh"
	end
  end