Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"

	config.vm.synced_folder ".", "/vagrant_data"

	# Máquina Master (wilSW
	config.vm.define "wilS" do |control|
	control.vm.hostname = "wilS"
	control.vm.network "private_network", ip: "192.168.56.110"
	control.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	end
	control.vm.provision "shell", path: "scripts/server/entrypoint.sh"
	end

	# Máquina Worker wilSW
	config.vm.define "wilSW" do |control|
	control.vm.hostname = "wilSW"
	control.vm.network "private_network", ip: "192.168.56.111"
	control.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 2
	end
	control.vm.provision "shell", path: "scripts/worker/entrypoint.sh"
	end
end